GET http://localhost:3003/api/blogs

###
POST http://localhost:5000/api/blogs
Content-Type: application/json

{
    "title" : "Why we use Mongoose js?",
    "image":"https://images.unsplash.com/photo-1553028429-58f931c6b716?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1170&q=80",
    "category": [
        "Computer Science",
        "Database",
        "Programming",
        "Mongodb"
    ],
    "desc" : "Let's face it, writing MongoDB validation, casting and business logic boilerplate is a drag. That's why we wrote Mongoose.''\n' '\n'Now say we like fuzzy kittens and want to record every kitten we ever meet in MongoDB. The first thing we need to do is include mongoose in our project and open a connection to the test database on our locally running instance of MongoDB.'\n''\n'Mongoose provides a straight-forward, schema-based solution to model your application data. It includes built-in type casting, validation, query building, business logic hooks and more, out of the box."
}