GET http://localhost:5000/api/blogs

###
POST http://localhost:5000/api/blogs
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InNhbWEiLCJpZCI6IjYzZTgxMTUwY2JlNDExZGY0ZDM1OTVkYiIsImlhdCI6MTY3NjE5NjI2Mn0.WGCFrTKlypFMRYM1GaTTcqHMOOBEgfOiPGwLMVrPMZI

{
    "title" : "HTTP authentication.",
    "image":"https://developer.mozilla.org/en-US/docs/Web/HTTP/Authentication/http-auth-sequence-diagram.png",
    "category": [
        "Computer Science",
        "Database",
        "Programming",
        "HTTP"
    ],
    "desc" : "Redux is a predictable state container for JavaScript apps.  It helps you write applications that behave consistently, run in different environments (client, server, and native), and are easy to test. On top of that, it provides a great developer experience, such as live code editing combined with a time traveling debugger.  You can use Redux together with React, or with any other view library. It is tiny (2kB, including dependencies), but has a large ecosystem of addons available."
}

###
POST http://localhost:5000/api/users
Content-Type: application/json

{
    "username" : "zillur",
    "name": "Zillur Rahman",
    "password": "1234567890"
}

###
DELETE  http://localhost:5000/api/users/62f5ffe5b9783571bd2adfae

###
POST http://localhost:5000/api/login
Content-Type: application/json

{
    "username": "sama",
    "password": "1234567890"
}